name: Fetch Urban Dictionary Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Urban Dictionary fetcher
      id: fetcher
      run: |
        OUTPUT=$(python fetch_ud.py)
        echo "$OUTPUT"
        echo "entries_added=$OUTPUT" >> $GITHUB_OUTPUT
    
    - name: Log new entries
      run: echo "✅ ${{ steps.fetcher.outputs.entries_added }}"
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add data/ dictionary/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update slang data"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
